version: '3'
services:
  myapp-main:
    image: s4_sprint2:latest
    ports:
      - 8080:8080
    environment:
      # - spring.datasource.url=jdbc:mysql://database-2.coqc1sowfzyu.ca-central-1.rds.amazonaws.com:3306/winter_2022
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/s4_sprint2
      - spring.datasource.password=C0ding!sH!p21
      - spring.datasource.username=root